[tool.ruff]
line-length = 120
target-version = "py312"
lint.select = ["E4", "E7", "E9", "F", "I"]
lint.ignore = ["F401"]
lint.fixable = ["ALL"]

[tool.pyright]
autoSearchPaths = true
typeCheckingMode = "strict"
reportUnusedImport = false
reportUnusedVariable = false
